# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]

# Setup
title:               Thomas Yancey
tagline:             'top notch blog'
description:         'A blog'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->